name: Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'target environment'
        required: true
        default: 'dev'

jobs:
  env_validation:
    if: contains(['dev', 'demo', 'production'], github.event.inputs.deploy_env)
  deployment:
    needs: ['env_validation']
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_env }}
    steps:
      - name: build_container...
