name: Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'target environment'
        required: true
  push:
    branches:
      - master

jobs:
  env_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set environment
        run: |
          [[ ${{ github.ref }} = 'master' || ${{ github.event_name }} == 'push' ]] && echo "DEPLOY_ENV=dev" >> $GITHUB_ENV || echo "DEPLOY_ENV=${{ github.event.inputs.deploy_env }}" >> $GITHUB_ENV
      - name: validate env
        if: ($DEPLOY_ENV != 'dev' && $DEPLOY_ENV != 'demo' && $DEPLOY_ENV != 'production')
        run: |
          echo "deploy environment has to be one of 'dev'/'demo'/'production'. Received: ${{ github.event.inputs.deploy_env }}"
          exit 1
  deployment:
    needs: ['env_validation']
    runs-on: ubuntu-latest
    environment: $DEPLOY_ENV
    if: success()
    steps:
      - name: deploy
        run: echo "deploy $DEPLOY_ENV, ${{ github.event.inputs.secret_1 }}"
