name: Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'target environment'
        required: true

jobs:
  env_validation:
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy_env != 'dev' && github.event.inputs.deploy_env != 'demo' && github.event.inputs.deploy_env != 'production'
    steps:
      - name: validate env
        run: |
          echo "deploy environment has to be one of 'dev'/'demo'/'production'. Received: ${{ github.event.inputs.deploy_env }}"
          exit 1
  deployment:
    needs: ['env_validation']
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_env }}
    if: success()
    steps:
      - name: deploy
        run: echo "deploy ${{ github.event.inputs.deploy_env }}, ${{ github.event.inputs.secret_1 }}"
