name: Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'target environment'
        required: true
  push:
    branches:
      - master

jobs:
  env_processing:
    runs-on: ubuntu-latest
    outputs:
      deploy_env: ${{ steps.output_deploy_env.outputs.deploy_env }}
    steps:
      - uses: actions/checkout@v2
      - id: set_environment
        run: |
          [[ ${{ github.ref }} == 'refs/heads/master' && ${{ github.event_name }} == 'push' ]] && echo "DEPLOY_ENV=dev" >> $GITHUB_ENV || echo "DEPLOY_ENV=${{ github.event.inputs.deploy_env }}" >> $GITHUB_ENV
      - id: output_deploy_env
        run: |
          echo "::set-output name=deploy_env::${{ env.DEPLOY_ENV }}"
      - id: fail_on_invalid_env
        if: (env.DEPLOY_ENV != 'dev' && env.DEPLOY_ENV != 'demo' && env.DEPLOY_ENV != 'production')
        run: |
          echo "deploy environment has to be one of 'dev'/'demo'/'production'. Received: ${{ github.event.inputs.deploy_env }}"
          exit 1
  deployment:
    needs: ['env_processing']
    runs-on: ubuntu-latest
    environment: ${{ needs.env_processing.outputs.deploy_env }}
    if: success()
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack - deploy start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SPECTRAL_SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: actions url
          SLACK_USERNAME: Deployment
          SLACK_ICON: "https://spectralops.io/wp-content/themes/spectral-theme/assets/images/favicon/favicon.ico"
          SLACK_FOOTER: ""
          SLACK_COLOR: "#005aaf"
          SLACK_MESSAGE: "@here *${{ needs.env_processing.outputs.deploy_env }}* deploy - started"
          SLACK_LINK_NAMES: true
      - id: deploy
        run: |
          echo "deploy ${{ needs.env_processing.outputs.deploy_env }}, ${{ secrets.secret_1 }}"
      - name: Notify Slack - deploy finished
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SPECTRAL_SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: actions url
          SLACK_USERNAME: Deployment
          SLACK_FOOTER: ""
          SLACK_ICON: "https://spectralops.io/wp-content/themes/spectral-theme/assets/images/favicon/favicon.ico"
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "@here *${{ needs.env_processing.outputs.deploy_env }}* deploy - ${{ steps.deploy.outcome }}"
          SLACK_LINK_NAMES: true
      - id: call_e2e_tests
        name: Call E2E workflow
        uses: ./.github/actions/e2e_test/action.yml
