name: Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'target environment'
        required: true
  push:
    branches:
      - master


jobs:
  env_processing:
    runs-on: ubuntu-latest
    outputs:
      deploy_env: ${{ steps.output_deploy_env.outputs.depenv }}
    steps:
      - uses: actions/checkout@v2
      - name: set_environment
        run: |
          [[ ${{ github.ref }} == 'refs/heads/master' && ${{ github.event_name }} == 'push' ]] && echo "DEPLOY_ENV=dev" >> $GITHUB_ENV || echo "DEPLOY_ENV=${{ github.event.inputs.deploy_env }}" >> $GITHUB_ENV
      - name: validate env
        if: (env.DEPLOY_ENV != 'dev' && env.DEPLOY_ENV != 'demo' && env.DEPLOY_ENV != 'production')
        run: |
          echo "deploy environment has to be one of 'dev'/'demo'/'production'. Received: ${{ github.event.inputs.deploy_env }}"
          exit 1
      - name: output_deploy_env
        run: echo "::set-output name=depenv::knknknk"
      - name: print_out
        run: echo "depenv->${{ toJson(steps) }}"
  deployment:
    needs: ['env_processing']
    runs-on: ubuntu-latest
    environment: ${{ needs.env_processing.outputs.deploy_env }}
    if: success()
    steps:
      - name: Notify Slack - start deploy
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SPECTRAL_SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: actions url
          SLACK_USERNAME: Deployment
          SLACK_ICON: "https://spectralops.io/wp-content/themes/spectral-theme/assets/images/favicon/favicon.ico"
          SLACK_FOOTER: ""
          SLACK_COLOR: "#0000af"
          SLACK_MESSAGE: "@here [${{ needs.env_processing.outputs.deploy_env }}] deploy starting!"
          SLACK_LINK_NAMES: true
      - name: deploy
        run: echo "deploy ${{ needs.env_processing.outputs.depenv }}, env->${{ toJson(needs.env_processing) }}, ${{ secrets.secret_1 }}"
