name: Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'target environment'
        required: true
        default: 'dev'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_env }}
    if: github.event.inputs.deploy_env == 'dev' || github.event.inputs.deploy_env == 'demo' || github.event.inputs.deploy_env == 'production'
    steps:
      - name: deploy
        run: echo "deploy ${{ github.event.inputs.deploy_env }}, ${{ github.event.inputs.secret_1 }}"
